/**
 * AccessPage — Payment Guide & Access Request Form
 *
 * Public-facing enrollment page where students can:
 * - View 3 payment methods (Bank Islami, EasyPaisa, PayPal)
 * - Follow step-by-step enrollment guide
 * - Submit an access request form
 * - Contact via WhatsApp support
 *
 * Inspired by the typing master site enrollment flow.
 */

import { useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import {
  Building2,
  Smartphone,
  CreditCard,
  CheckCircle2,
  ChevronRight,
  MessageCircle,
  AlertCircle,
} from "lucide-react";
import { saveAccessRequest, type AccessRequest } from "../store/accessStore";
import { WhatsAppFloat } from "../components/WhatsAppFloat";

export const Route = createFileRoute("/access")({
  component: AccessPage,
});

// ─── Select Payment Methods ──────────────────────────────────────────────

const PAYMENT_METHODS = [
  {
    id: "bank-islami",
    name: "Bank Islami",
    icon: <Building2 className="h-8 w-8" />,
    color: "bg-sky-100 border-sky-200 text-sky-700",
    details: "Bank Name: Bank Islami Pakistan LTD.\nAccount Title: Ahsan Mahmood Khan\nAccount Number: PK98BKIP0303800235070201\nAmount: $1 / 300 PKR",
    warning: "\u26a0\ufe0f Transfer the enrollment fee of $1 / 300 PKR and capture your electronic transaction bank receipt.",
  },
  {
    id: "easypaisa",
    name: "EasyPaisa",
    icon: <Smartphone className="h-8 w-8" />,
    color: "bg-emerald-50 border-emerald-200 text-emerald-700",
    details: "Account Name: Ahsan Mahmood Khan\nAccount Number: 03105265337",
    warning: "\u26a0\ufe0f Transfer $1 / 300 PKR to the wallet and enter the unique ID generated by EasyPaisa in the transaction field.",
  },
  {
    id: "paypal",
    name: "PayPal",
    icon: <CreditCard className="h-8 w-8" />,
    color: "bg-indigo-50 border-indigo-200 text-indigo-700",
    details: "Account Title: Ahsan Mahmood Khan\nAccount Number: 333591114926\nRouting Number: 031101279",
    warning: "\u26a0\ufe0f International registration fee is $1 USD. Provide the generated PayPal receipt ID as your Transaction ID.",
  },
];

const ENROLLMENT_STEPS = [
  { number: 1, title: "Choose Select Payment Method", desc: "Select Bank Islami, EasyPaisa, or PayPal" },
  { number: 2, title: "Make Payment", desc: "Send the enrollment fee using the account details" },
  { number: 3, title: "Note Transaction ID", desc: "Save the transaction/reference ID from your payment" },
  { number: 4, title: "Submit Request Form", desc: "Fill in your details below with the transaction ID" },
  { number: 5, title: "Wait for Approval", desc: "Admin will verify and approve within 24 hours" },
  { number: 6, title: "Start Learning!", desc: "Use your phone number to log in and access the EHR simulator" },
];

// ─── Component ────────────────────────────────────────────────────

function AccessPage() {
  const [formData, setFormData] = useState({
    fullName: "",
    phone: "",
    email: "",
    paymentMethod: "easypaisa" as AccessRequest["paymentMethod"],
    transactionId: "",
  });
  const [submitted, setSubmitted] = useState(false);
  const [error, setError] = useState("");
  const [hasConfirmedReceipt, setHasConfirmedReceipt] = useState(false);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setError("");

    // Basic validation
    if (!formData.fullName.trim() || !formData.phone.trim() || !formData.transactionId.trim()) {
      setError("Please fill in all required fields");
      return;
    }

    const request: AccessRequest = {
      id: `req-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
      fullName: formData.fullName.trim(),
      phone: formData.phone.trim(),
      email: formData.email.trim(),
      paymentMethod: formData.paymentMethod,
      transactionId: formData.transactionId.trim(),
      submittedAt: new Date().toISOString(),
      status: "pending",
    };

    saveAccessRequest(request);
    setSubmitted(true);
  };

  if (submitted) {
    return (
      <div className="flex min-h-dvh flex-col items-center justify-center bg-gradient-to-br from-sky-50 to-blue-100 p-4">
        <div className="w-full max-w-md rounded-2xl border border-green-200 bg-white p-8 text-center shadow-lg">
          <CheckCircle2 className="mx-auto mb-4 h-16 w-16 text-green-500" />
          <h2 className="text-xl font-bold text-slate-800">Request Submitted!</h2>
          <p className="mt-2 text-sm text-slate-500">
            Your access request has been received. An admin will review your payment and approve your account within 24 hours.
          </p>
          <p className="mt-4 text-sm text-slate-500">
            Your Login ID: <span className="font-bold text-sky-600">{formData.phone}</span>
          </p>
          <Link
            to="/login"
            className="mt-6 inline-block rounded-lg bg-sky-500 px-6 py-2.5 text-sm font-medium text-white hover:bg-sky-600"
          >
            Go to Login
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-dvh bg-gradient-to-br from-sky-50 to-blue-100">
      {/* Header */}
      <header className="flex items-center justify-between border-b border-sky-200 bg-white/80 px-4 py-3 backdrop-blur">
        <div className="flex items-center gap-3">
          <img
            src="/healthcarehustlers-logo.png"
            alt="Healthcare Hustlers"
            className="h-7 w-auto"
            style={{ maxWidth: "160px" }}
          />
        </div>
        <nav className="flex items-center gap-3 text-xs">
          <Link to="/login" className="font-medium text-sky-600 hover:text-sky-700">Login</Link>
          <Link to="/" className="rounded-lg bg-sky-500 px-3 py-1.5 font-medium text-white hover:bg-sky-600">Home</Link>
        </nav>
      </header>

      <div className="mx-auto max-w-4xl p-4 py-8">
        {/* Title */}
        <div className="mb-8 text-center">
          <h1 className="text-2xl font-bold text-slate-800">Payment Guide & Enrollment</h1>
          <p className="mt-1 text-sm text-slate-500">
            Follow the steps below to get access to the EHR Simulation Portal
          </p>
        </div>

        {/* Step-by-step guide */}
        <div className="mb-8">
          <h2 className="mb-4 text-lg font-semibold text-slate-700">Enrollment Steps</h2>
          <div className="grid grid-cols-1 gap-3 md:grid-cols-3">
            {ENROLLMENT_STEPS.map((step) => (
              <div
                key={step.number}
                className="flex items-start gap-3 rounded-xl border border-slate-200 bg-white p-4 shadow-sm"
              >
                <div className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-sky-100 text-xs font-bold text-sky-600">
                  {step.number}
                </div>
                <div>
                  <p className="text-sm font-medium text-slate-700">{step.title}</p>
                  <p className="text-xs text-slate-400">{step.desc}</p>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Select Payment Methods */}
        <div className="mb-8">
          <h2 className="mb-4 text-lg font-semibold text-slate-700">Select Payment Method</h2>
          <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
            {PAYMENT_METHODS.map((method) => (
              <div
                key={method.id}
                className={`rounded-xl border-2 p-4 transition-all ${
                  formData.paymentMethod === method.id
                    ? "border-sky-400 bg-sky-50 shadow-md"
                    : "border-slate-200 bg-white hover:border-sky-200"
                }`}
              >
                <div className="mb-2 flex items-center gap-2">
                  <div className={`rounded-lg p-2 ${method.color}`}>{method.icon}</div>
                  <span className="font-semibold text-slate-700">{method.name}</span>
                </div>
                <pre className="whitespace-pre-wrap text-xs text-slate-500">{method.details}</pre>
                {method.warning && (
                  <p className="mt-2 rounded-lg bg-amber-50 p-2 text-[10px] font-medium text-amber-700">
                    {method.warning}
                  </p>
                )}
                <button
                  onClick={() =>
                    setFormData({ ...formData, paymentMethod: method.id as AccessRequest["paymentMethod"] })
                  }
                  className={`mt-3 w-full rounded-lg py-1.5 text-xs font-medium transition-colors ${
                    formData.paymentMethod === method.id
                      ? "bg-sky-500 text-white"
                      : "bg-slate-100 text-slate-600 hover:bg-slate-200"
                  }`}
                >
                  {formData.paymentMethod === method.id ? "Selected" : "Select"}
                </button>
              </div>
            ))}
          </div>
        </div>

        {/* Access Request Form */}
        <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-lg">
          <h2 className="mb-4 text-lg font-semibold text-slate-700">Access Request Form</h2>
          <form onSubmit={handleSubmit} className="space-y-4">
            <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
              <div>
                <label className="mb-1 block text-xs font-medium text-slate-600">
                  Student Full Name *
                </label>
                <input
                  type="text"
                  value={formData.fullName}
                  onChange={(e) => setFormData({ ...formData, fullName: e.target.value })}
                  placeholder="John Doe"
                  className="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-sky-400 focus:ring-1 focus:ring-sky-400"
                />
              </div>
              <div>
                <label className="mb-1 block text-xs font-medium text-slate-600">
                  Phone Number (Login ID) *
                </label>
                <input
                  type="tel"
                  value={formData.phone}
                  onChange={(e) => setFormData({ ...formData, phone: e.target.value })}
                  placeholder="03001234567"
                  className="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-sky-400 focus:ring-1 focus:ring-sky-400"
                />
              </div>
              <div>
                <label className="mb-1 block text-xs font-medium text-slate-600">Email</label>
                <input
                  type="email"
                  value={formData.email}
                  onChange={(e) => setFormData({ ...formData, email: e.target.value })}
                  placeholder="student@example.com"
                  className="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-sky-400 focus:ring-1 focus:ring-sky-400"
                />
              </div>
              <div>
                <label className="mb-1 block text-xs font-medium text-slate-600">Select Payment Method</label>
                <select
                  value={formData.paymentMethod}
                  onChange={(e) =>
                    setFormData({
                      ...formData,
                      paymentMethod: e.target.value as AccessRequest["paymentMethod"],
                    })
                  }
                  className="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-sky-400 focus:ring-1 focus:ring-sky-400"
                >
                  <option value="easypaisa">EasyPaisa</option>
                  <option value="bank-islami">Bank Islami</option>
                  <option value="paypal">PayPal</option>
                </select>
              </div>
              <div className="md:col-span-2">
                <label className="mb-1 block text-xs font-medium text-slate-600">
                  Unique Transaction ID *
                </label>
                <input
                  type="text"
                  value={formData.transactionId}
                  onChange={(e) => setFormData({ ...formData, transactionId: e.target.value })}
                  placeholder="Enter the transaction/reference ID from your payment"
                  className="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-sky-400 focus:ring-1 focus:ring-sky-400"
                />
              </div>
            </div>

            {/* ─── Pricing Note ─── */}
            <div className="rounded-lg bg-amber-50 p-3 text-xs text-amber-700">
              <p className="font-medium">Note: $1 provides access to one RCM stage only.</p>
              <p className="mt-0.5">Each stage (Scribe, Coder, Biller, Prior Auth, AR Voice Specialist) costs $1 separately.</p>
            </div>

            {/* ─── WhatsApp Receipt Confirmation ─── */}
            <div className="rounded-lg bg-green-50 p-4">
              <p className="mb-2 text-xs font-medium text-green-800">
                Send your payment receipt to our WhatsApp for verification:
              </p>
              <a
                href="https://api.whatsapp.com/send/?phone=923350340888&text&type=phone_number&app_absent=0"
                target="_blank"
                rel="noopener noreferrer"
                className="inline-flex items-center gap-1.5 rounded-lg bg-green-600 px-3 py-1.5 text-xs font-medium text-white hover:bg-green-500 transition-colors"
              >
                <MessageCircle className="h-3.5 w-3.5" />
                Send Receipt on WhatsApp
              </a>
              <div className="mt-3">
                <p className="mb-2 text-xs font-medium text-slate-600">
                  Have you sent the payment receipt to our WhatsApp number?
                </p>
                <div className="flex items-center gap-4">
                  <label className="flex items-center gap-1.5 cursor-pointer">
                    <input
                      type="radio"
                      name="receiptConfirmed"
                      checked={hasConfirmedReceipt}
                      onChange={() => setHasConfirmedReceipt(true)}
                      className="h-4 w-4 accent-green-600"
                    />
                    <span className="text-xs text-slate-700">Yes</span>
                  </label>
                  <label className="flex items-center gap-1.5 cursor-pointer">
                    <input
                      type="radio"
                      name="receiptConfirmed"
                      checked={!hasConfirmedReceipt}
                      onChange={() => setHasConfirmedReceipt(false)}
                      className="h-4 w-4 accent-red-400"
                    />
                    <span className="text-xs text-slate-700">No</span>
                  </label>
                </div>
              </div>
            </div>

            {error && (
              <div className="flex items-center gap-2 rounded-lg bg-red-50 p-3 text-sm text-red-600">
                <AlertCircle className="h-4 w-4" />
                {error}
              </div>
            )}

            <button
              type="submit"
              disabled={!hasConfirmedReceipt}
              className={`flex w-full items-center justify-center gap-2 rounded-lg py-3 text-sm font-medium text-white transition-colors ${
                hasConfirmedReceipt
                  ? "bg-sky-500 hover:bg-sky-600"
                  : "bg-slate-300 cursor-not-allowed"
              }`}
            >
              <ChevronRight className="h-4 w-4" />
              Submit Access Request
            </button>
          </form>
        </div>

        {/* WhatsApp Support */}
        <div className="mt-6 rounded-2xl border border-green-200 bg-green-50 p-6">
          <div className="flex items-start gap-4">
            <MessageCircle className="h-8 w-8 shrink-0 text-green-600" />
            <div>
              <h3 className="font-semibold text-green-800">Need Help? Contact Support</h3>
              <p className="mt-1 text-sm text-green-700">
                Have questions about payment or enrollment? Chat with us on WhatsApp.
              </p>
              <a
                href="https://api.whatsapp.com/send/?phone=923350340888&text&type=phone_number&app_absent=0"
                target="_blank"
                rel="noopener noreferrer"
                className="mt-3 inline-flex items-center gap-2 rounded-lg bg-green-600 px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-green-500"
              >
                <MessageCircle className="h-4 w-4" />
                WhatsApp Support
              </a>
            </div>
          </div>
        </div>
      </div>

      <WhatsAppFloat />
    </div>
  );
}